@startuml Aufbau
skinparam componentStyle uml2
skinparam monochrome true

interface "LAN" as lanPs4
interface "Bluetooth" as btPs4
interface "LAN*" as harmonyIn

package "Raspberry Pi - Hassbian" {
  interface "CLI" as cliPs4W
  interface "LAN" as lanHass
  lanHass - [Homeassistant]
  [Homeassistant] --> cliPs4W
  cliPs4W - [PS4-waker]
}

[Playstation 4] -- lanPs4
btPs4 - [Playstation 4]
lanPs4 <--[PS4-waker]

package "Smartphone" {
  [Harmony App] --> harmonyIn
}

harmonyIn - [Harmony Hub]
[Harmony Hub] -> btPs4
[Harmony Hub] --> lanHass

@enduml