@startuml ps-ein-harmony
skinparam componentStyle uml2
skinparam monochrome true

participant "home.myharmony.com" as mh
participant "Harmony Hub" as hu
participant "Hassbian" as ha
participant "PS4" as p


hu -> ha: HTTP-GET-Request
activate ha
ha -> hu: HTTP-Response
deactivate ha

hu -> ha: HTTP-PUT-Request
activate ha

hu -> mh : Verbindungsaufbau &\nTLS-Handhaske
activate mh

ha -> hu: HTTP-Response
deactivate ha


ha -> p : WAKEUP-Paket

mh -> hu : Schließen der Verbindung
deactivate mh


hu -> ha: HTTP-GET-Request
activate ha
ha -> hu: HTTP-Response
deactivate ha

ha -> p : WAKEUP-Paket
ha -> p : LAUNCH-Paket

ha -> p : Aufbau der\nTCP-Verbindung
activate p
ha -> p : Schließen der\nTCP-Verbindung
deactivate p

hu -> ha: HTTP-GET-Request
activate ha
ha -> hu: HTTP-Response
deactivate ha

hu -> mh : Verbindungsaufbau &\nTLS-Handhaske
activate mh
mh -> hu : Schließen der Verbindung
deactivate mh
hu -> mh : Verbindungsaufbau &\nTLS-Handhaske
activate mh
mh -> hu : Schließen der Verbindung
deactivate mh

@enduml